---
- name: Create datavg
  community.general.lvg:
    vg: data
    pvs: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

- name: Create consul lv
  community.general.lvol:
    vg: data
    lv: consul
    size: 95G

- name: Format consul lv
  community.general.filesystem:
    fstype: xfs
    dev: /dev/data/consul

- name: Mount consul drive
  ansible.posix.mount:
    path: /opt/consul/data
    src: /dev/data/consul
    fstype: xfs
    boot: true
    state: mounted

- name: Own Consul drive
  ansible.builtin.file:
    path: /opt/consul/data
    owner: consul
    group: consul
    mode: "0770"

# Start Vault Agent
- name: Set Vault Agent ENV
  ansible.builtin.template:
    src: etc/vault.d/vault.env
    dest: /etc/vault.d/vault.env
    mode: "0644"
# End Vault Agent

# Start Consul
- name: Create Consul Certificates
  ansible.builtin.command: >-
    step ca certificate {{ ansible_fqdn }}
    /opt/consul/tls/https.crt
    /opt/consul/tls/https.key
    --ca-url https://step-ca.us-homelab1.hl.rmb938.me:8443
    --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
  args:
    creates: "/opt/consul/tls/https.crt"

- name: Own Consul certificates
  ansible.builtin.file:
    path: /opt/consul/tls/{{ item }}
    owner: consul
    group: consul
    mode: "0600"
  with_items:
    - https.crt
    - https.key

- name: Cron to renew consul certificates
  ansible.builtin.cron:
    name: "renew consul certificates"
    special_time: "hourly"
    # Rekey needs to happen against the CA, RA's don't support rekey
    # https://smallstep.com/docs/step-ca/registration-authority-ra-mode/#stepcas-limitations
    job: >-
      step ca rekey /opt/consul/tls/https.crt
      /opt/consul/tls/https.key
      --ca-url https://step-ca.us-homelab1.hl.rmb938.me
      --root /usr/local/share/ca-certificates/smallstep-homelab-prod.crt
      --force --expires-in 720h --exec "systemctl try-reload-or-restart consul"
    state: present
# End Consul

# Start Consul Template for Consul
- name: Configure Consul Template for Consul
  ansible.builtin.template:
    src: etc/consul-template/consul-template-consul.hcl
    dest: /etc/consul-template/consul-template-consul.hcl
    mode: "0644"
    owner: consul
    group: consul
  register: consul_template_consul_config

- name: Place Consul Template for Consul Templates Files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/consul-template/templates/consul/{{ item | basename }}"
    mode: "0644"
    owner: consul
    group: consul
  with_fileglob:
    - ../files/etc/consul-template/templates/consul/*.ctmpl
  register: consul_template_consul_templates_files

- name: Place Consul Template for Consul Templates Templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/consul-template/templates/consul/{{ item | basename }}"
    mode: "0644"
    owner: consul
    group: consul
  with_fileglob:
    - ../templates/etc/consul-template/templates/consul/*.ctmpl
  register: consul_template_consul_templates

- name: Start and enable Consul Template for Consul
  ansible.builtin.systemd:
    name: consul-template-consul
    state: started
    enabled: true

- name: Restart Consul Template for Consul if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: consul-template-consul
    state: reloaded
  when: consul_template_consul_templates.changed or consul_template_consul_config.changed or consul_template_consul_templates_files.changed
# End Consul Template for Consul
